### ISSUE TITLE
Sample application not running

### ISSUE THREAD

**Issue by neversun** [nekrondev/jolla_go#1]
environment: SailfishOSSDK-Beta-1511-Qt5-linux-64 with unmodified Sailfish VM
1. ssh into emulator as mersdk `ssh -p 2222 -i ~/SailfishOS/vmshare/ssh/private_keys/engine/mersdk mersdk@localhost`
2. build dewpoint calc `mb2 build`
3. install rpm with `./deploy`
4. ssh into emulator as nemo `ssh -p 2223 -i ~/SailfishOS/vmshare/ssh/private_keys/SailfishOS_Emulator/nemo nemo@localhost`
5. run `harbour-dewpointcalc`

Until 5. everthing is fine. But running the app is showing errors in console. Running app via app launcher does nothing more than closing the app after a few seconds in multitasking/home view.

Errors of 5.:

``` bash
2016/01/26 21:02:04 capi.cpp:28: "Found i18n for de_DE" 
2016/01/26 21:02:04 silicatheme.cpp:380: No pixel ratio defined. Check your device configuration! 
2016/01/26 21:02:04 silicatheme.cpp:385: Defaulting to pixel ratio 1.0 
2016/01/26 21:02:04 declarativeimageprovider.cpp:104: No pixel ratio defined. Check your device configuration! 
2016/01/26 21:02:04 declarativeimageprovider.cpp:109: Defaulting to pixel ratio 1.0 
2016/01/26 21:02:04 declarativewindow.cpp:93: No default allowed orientations defined. Check your device configuration! 
Calc: 0, 0
Calc: ctrl.temp 0
2016/01/26 21:02:04 Dewpoint.qml:46: Index is 0
Calc: 0, 0
Calc: ctrl.temp 0
2016/01/26 21:02:04 qwaylandeglclientbufferintegration.cpp:62: Using Wayland-EGL 
2016/01/26 21:02:04 declarativecoverwindow.cpp:69: DeclarativeCoverWindow: You should be calling QQuickWindow::setDefaultAlphaBuffer(true) before creating windows. Failing to do so may result in suboptimal performance.
2016/01/26 21:02:04 declarativecoverwindow.cpp:70: DeclarativeCoverWindow: You also won't have cover transparency.
Trying to load settings from /home/nemo/.config/harbour-dewpointcalc/settings_0.1.1.json
Calc: 21, 0
Calc: ctrl.temp 21
Calc: 21, 0
Calc: ctrl.temp 21
2016/01/26 21:02:04 qwaylandglcontext.cpp:386: QWaylandGLContext::makeCurrent: eglError: 3009, this: 0x8e97d08 
```

**Comment by nekrondev** [comment]
Interesting to hear about this behaviour. Usually if QML or go runtime crashes you should get a QML or GO runtime panic to stdout. Maybe change RAM size for the SFOS emulator to avoid OOM killer to kick in? Other pointers are to add some fmt.Print() lines to find out where the application exits. 

The log entries you see on 5) are common when launching a Sailfish Silica application, so don't worry about them.

**Comment by aebruno** [comment]
Hello and thanks for the amazing work getting go running on Jolla! I was having the same error and was able to fix the app with a few simple tweaks. I submitted a pull request with the fix. 

Cheers!

**Comment by nekrondev** [comment]
Yes thats right. I added specific Sailfish\* launcher methods to the original GO QML C++ bindings to fixed issues I had getting cover pages to work (with the generic Qt-based approch cover views won't work). Other than that I guess it is a must now to use them!
